version: 0.2
env:
  parameter-store:
    ANSIBLE_PRIVATE_KEY: "/ansible_demo/ansible_private_key"

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install -r requirements.txt -q
      - mkdir -p ~/.ec2
      - echo "$ANSIBLE_PRIVATE_KEY" > ~/.ec2/ajb5779-codebuild-keypair.pem
      - chmod 400 ~/.ec2/ajb5779-codebuild-keypair.pem

  build:
    commands:
      ansible-playbook -i inventory/hosts install_nginx.yaml
      
