version: 0.2
env:
  parameter-store:
    ANSIBLE_PRIVATE_KEY: "/ansible_demo/ansible_private_key"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt -q
      - mkdir -p ~/.ssh
      - echo "$ANSIBLE_PRIVATE_KEY" > ~/.ssh/ansible
      - chmod 600 ~/.ssh/ansible
  build:
    commands:
      - ansible-playbook -i inventory/hosts install_nginx.yaml -vvv
