---
- name: Nginx installation
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Installing Systems nginx
      package:
        name:
          - nginx
        state: present

    - name: Start/reload NGINX
          service:
            name: nginx
            state: restarted
            enabled: true
    
